### ISSUE TITLE
Consider label-schema.org?

### ISSUE THREAD

**Issue by beddari** [bfirsh/whalebrew#6]
Hi, awesome project, seems like this idea was finally ready for someone to pick up and run with!!

Would you consider adopting http://label-schema.org/rc1/ ? Not sure if you are aware of it, but I think it would make a lot of sense in this context

**Comment by bfirsh** [comment]
Yep, for sure! There just wasn't anything useful in there I could use. "docker.cmd" is not flexible enough. Description is something we could adopt to describe what packages are, perhaps.

The Whalebrew labels are something that could be incorporated into label schema, perhaps.

**Comment by beddari** [comment]
Care to expand on why docker.cmd wasn't useful? I'd say this use case would be a primary acid test for that to be useful. So much as if you've found it not to work we should ask to get it changed.

**Comment by bfirsh** [comment]
Several reasons:

1. The command-line arguments need to be changed at runtime based on various things, and splicing command-line arguments into an arbitrary string is very difficult and fragile. Splicing with a list of arguments is a bit better, but still fragile.
2. I want to be able to store the configuration as YAML so it is user configurable. I could have stored just a "docker run" command which the user could edit, but then that has the same problem as (1).
3. I want the configuration to be machine readable, similar to (2).

Thus, I opted for specifying the options separately as labels (environment and volumes) instead of just an arbitrary docker run command.

**Comment by bfirsh** [comment]
https://github.com/label-schema/label-schema.org/issues/19
